"""
Centralized AI Command Console — Gemini function-calling engine.

Interprets free-form natural language commands and maps them to PermitIQ
actions. Read-only tools execute immediately; mutating tools return a
confirmation preview so the user can approve before anything changes.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any

from dotenv import load_dotenv
load_dotenv()

import google.genai as genai
from google.genai import types

from app.firebase_config import db

REASONING_MODEL = os.getenv("GEMINI_REASONING_MODEL", "gemini-2.5-flash")
_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

SYSTEM_PROMPT = """You are the PermitIQ AI Command Console — an intelligent assistant for HR managers and compliance officers at Malaysian SMEs managing foreign worker permits.

You help users understand compliance status, trigger workflows, and get answers about workers — all in plain English.

Domain knowledge:
- Workers go through permit stages: JTKSM approval → KDN quota → VDR submission → arrival verification → FOMEMA medical screening → PLKS issuance
- Compliance requires: valid passport (12+ months), work permit (PLKS), annual FOMEMA health check, MTLM levy payment, Act 446 housing certificate
- Critical deadlines are tracked in the Renewal Calendar (passport, permit, annual health checkup)
- Contracts are PDF employment agreements — generated by admin, signed by worker, then reviewed

Available pages the user can navigate to:
Overview, Worker Workflows, Permit Stages Board, Alerts, Workers, Approvals Queue, Contract Generator, Gov Portal (Demo), Sync With Gov Records, Cost Simulator, Worker Compliance Graph, Renewal Calendar, Invite Workers.

Rules:
- For mutating actions (start workflow, scan alerts), always call the tool — the user will be shown a confirmation card before execution.
- For read-only queries, call the tool and summarize results clearly.
- Use bullet points for lists. Highlight names and numbers in bold.
- If you cannot find a worker by name, ask the user to clarify or check the Workers page.
- Be concise — 2–4 sentences maximum for narrative, then bullets for data."""


# ─── Tool schemas (Gemini function declarations) ──────────────────────────────

TOOL_SCHEMAS = [
    types.FunctionDeclaration(
        name="list_workers",
        description="List all workers with their names, IDs, sector, and compliance status.",
        parameters={
            "type": "object",
            "properties": {
                "status_filter": {
                    "type": "string",
                    "description": "Optional — filter by review_status: approved, pending, needs_review",
                },
            },
        },
    ),
    types.FunctionDeclaration(
        name="find_worker_by_name",
        description="Find a specific worker by name (partial match). Returns worker ID, name, and status.",
        parameters={
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Worker name or partial name, e.g. 'Ahmad' or 'Siti'",
                },
            },
            "required": ["name"],
        },
    ),
    types.FunctionDeclaration(
        name="list_alerts",
        description="List compliance alerts — expiring permits, expired passports, overdue FOMEMA.",
        parameters={
            "type": "object",
            "properties": {
                "severity": {
                    "type": "string",
                    "description": "Optional — filter by severity: critical, high, medium",
                },
            },
        },
    ),
    types.FunctionDeclaration(
        name="get_quota_balance",
        description="Get the company's remaining quota balance for hiring foreign workers by sector.",
        parameters={
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "string",
                    "description": "Company ID. Defaults to 'demo-company'.",
                },
            },
        },
    ),
    types.FunctionDeclaration(
        name="list_obligations",
        description="List upcoming renewal obligations for a specific worker (passport, permit, health checkup).",
        parameters={
            "type": "object",
            "properties": {
                "worker_id": {
                    "type": "string",
                    "description": "Worker ID, e.g. 'worker-001'",
                },
            },
            "required": ["worker_id"],
        },
    ),
    types.FunctionDeclaration(
        name="list_contracts",
        description="List employment contracts — their status (generated, signed, reviewed) and which worker they belong to.",
        parameters={
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "description": "Optional — filter by status: generated, signed, reviewed",
                },
            },
        },
    ),
    types.FunctionDeclaration(
        name="list_pending_handoffs",
        description="List pending tool handoffs — government portal actions waiting for human approval.",
        parameters={"type": "object", "properties": {}},
    ),
    types.FunctionDeclaration(
        name="simulate_mtlm_levy",
        description="Simulate the Multi-Tier Levy Mechanism (MTLM) cost for a given sector and worker headcount.",
        parameters={
            "type": "object",
            "properties": {
                "sector": {
                    "type": "string",
                    "description": "Industry sector: Manufacturing, Services, or Construction",
                },
                "current_foreign_count": {
                    "type": "integer",
                    "description": "Current number of foreign workers",
                },
                "current_local_count": {
                    "type": "integer",
                    "description": "Current number of local employees",
                },
                "new_foreign_workers": {
                    "type": "integer",
                    "description": "Additional foreign workers to simulate (default 0)",
                },
            },
            "required": ["sector", "current_foreign_count", "current_local_count"],
        },
    ),
    types.FunctionDeclaration(
        name="start_compliance_workflow",
        description="Start an automated compliance workflow for a specific worker — audits documents and triggers government filing steps.",
        parameters={
            "type": "object",
            "properties": {
                "worker_id": {
                    "type": "string",
                    "description": "Worker ID, e.g. 'worker-001'",
                },
            },
            "required": ["worker_id"],
        },
    ),
    types.FunctionDeclaration(
        name="scan_all_alerts",
        description="Scan all workers for compliance issues, expiring permits, and overdue tasks.",
        parameters={"type": "object", "properties": {}},
    ),
]

MUTATING_TOOLS = {"start_compliance_workflow", "scan_all_alerts"}


# ─── Tool handlers ────────────────────────────────────────────────────────────

def _worker_name(d: dict, doc_id: str) -> str:
    return (
        d.get("full_name")
        or (d.get("passport") or {}).get("full_name")
        or d.get("master_name")
        or doc_id
    )


def _handle_list_workers(args: dict) -> dict:
    status_filter = args.get("status_filter")
    workers = []
    for doc in db.collection("workers").stream():
        d = doc.to_dict() or {}
        rs = d.get("review_status", "unknown")
        if status_filter and rs != status_filter:
            continue
        workers.append({
            "worker_id": doc.id,
            "name": _worker_name(d, doc.id),
            "nationality": d.get("nationality") or (d.get("passport") or {}).get("nationality", ""),
            "sector": d.get("sector") or (d.get("general_information") or {}).get("sector", ""),
            "review_status": rs,
            "workflow_status": d.get("workflow_status", ""),
        })
    return {"workers": workers, "total": len(workers)}


def _handle_find_worker_by_name(args: dict) -> dict:
    query = (args.get("name") or "").lower()
    matches = []
    for doc in db.collection("workers").stream():
        d = doc.to_dict() or {}
        full = (_worker_name(d, "")).lower()
        if query in full:
            matches.append({
                "worker_id": doc.id,
                "name": _worker_name(d, doc.id),
                "review_status": d.get("review_status", ""),
                "workflow_status": d.get("workflow_status", ""),
            })
    return {"matches": matches, "count": len(matches)}


def _handle_list_alerts(args: dict) -> dict:
    severity_filter = args.get("severity")
    now = datetime.now()
    alerts = []
    for doc in db.collection("workers").stream():
        d = doc.to_dict() or {}
        name = _worker_name(d, doc.id)

        for date_key, alert_type, label in [
            (
                d.get("permit_expiry_date") or (d.get("general_information") or {}).get("permit_expiry_date"),
                "permit",
                "Permit",
            ),
            (
                d.get("passport_expiry_date") or (d.get("passport") or {}).get("expiry_date"),
                "passport",
                "Passport",
            ),
        ]:
            if not date_key:
                continue
            try:
                exp = datetime.fromisoformat(str(date_key))
                days = (exp - now).days
                if days < 0:
                    sev = "critical"
                    msg = f"{label} expired {abs(days)} days ago"
                elif days <= 30:
                    sev = "high"
                    msg = f"{label} expires in {days} days"
                elif days <= 90:
                    sev = "medium"
                    msg = f"{label} expires in {days} days"
                else:
                    continue
                if not severity_filter or sev == severity_filter:
                    alerts.append({"worker_id": doc.id, "name": name, "type": f"{alert_type}_expiry", "severity": sev, "message": msg})
            except Exception:
                pass

        if d.get("fomema_status", "").lower() in ("pending", ""):
            sev = "high"
            if not severity_filter or sev == severity_filter:
                alerts.append({"worker_id": doc.id, "name": name, "type": "fomema_pending", "severity": sev, "message": "FOMEMA medical screening pending"})

    return {"alerts": alerts, "total": len(alerts)}


def _handle_get_quota_balance(args: dict) -> dict:
    company_id = args.get("company_id", "demo-company")
    doc = db.collection("companies").document(company_id).get()
    if not doc.exists:
        return {"error": f"Company '{company_id}' not found"}
    d = doc.to_dict() or {}
    return {
        "company_name": d.get("company_name", ""),
        "quota_balance": d.get("quota_balance", {}),
        "quota_approved": d.get("quota_approved"),
        "jtksm_60k_status": d.get("jtksm_60k_status", ""),
    }


def _handle_list_obligations(args: dict) -> dict:
    worker_id = args["worker_id"]
    docs = db.collection("worker_obligations").where("worker_id", "==", worker_id).stream()
    obligations = sorted(
        [{"id": doc.id, **({k: v for k, v in (doc.to_dict() or {}).items()})} for doc in docs],
        key=lambda x: x.get("date") or "",
    )
    return {"worker_id": worker_id, "obligations": obligations}


def _handle_list_contracts(args: dict) -> dict:
    status_filter = args.get("status")
    contracts = []
    for doc in db.collection("contracts").stream():
        d = doc.to_dict() or {}
        if status_filter and d.get("status") != status_filter:
            continue
        contracts.append({
            "contract_id": doc.id,
            "worker_name": d.get("worker_name"),
            "worker_id": d.get("worker_id"),
            "status": d.get("status"),
            "created_at": d.get("created_at"),
        })
    return {"contracts": contracts, "total": len(contracts)}


def _handle_list_pending_handoffs(args: dict) -> dict:
    handoffs = []
    for doc in db.collection("pending_handoffs").stream():
        d = doc.to_dict() or {}
        if d.get("status") == "awaiting_confirmation":
            handoffs.append({
                "id": doc.id,
                "worker_id": d.get("worker_id"),
                "action_type": d.get("action_type"),
                "triggered_by": d.get("triggered_by"),
            })
    return {"pending_handoffs": handoffs, "total": len(handoffs)}


def _handle_simulate_mtlm_levy(args: dict) -> dict:
    from app.tools.compliance_tools import calculate_mtlm_levy
    try:
        return calculate_mtlm_levy(
            sector=args.get("sector", "Manufacturing"),
            current_foreign_count=int(args.get("current_foreign_count", 0)),
            current_local_count=int(args.get("current_local_count", 0)),
            new_foreign_workers=int(args.get("new_foreign_workers", 0)),
        )
    except Exception as e:
        return {"error": str(e)}


def _handle_start_compliance_workflow(args: dict) -> dict:
    worker_id = args["worker_id"]
    doc = db.collection("workers").document(worker_id).get()
    if not doc.exists:
        return {"error": f"Worker '{worker_id}' not found"}
    worker_data = doc.to_dict() or {}
    try:
        from app.agents.graph import compliance_graph
        from app.agents.state import create_initial_worker_state
        state = create_initial_worker_state(worker_data)
        state["worker_id"] = worker_id
        state["trace"] = []
        state["current_node"] = None
        config = {"configurable": {"thread_id": f"worker_{worker_id}", "checkpoint_ns": "compliance"}}
        result = compliance_graph.invoke(state, config)
        db.collection("workflows").document(worker_id).set({
            "worker_id": worker_id,
            "status": "active",
            "current_state": result,
            "started_at": datetime.now(timezone.utc).isoformat(),
            "last_updated": datetime.now(timezone.utc).isoformat(),
        })
        return {
            "worker_id": worker_id,
            "status": result.get("compliance_status"),
            "hitl_required": result.get("hitl_required", False),
            "alerts": result.get("alerts", []),
        }
    except Exception as e:
        return {"error": str(e)}


def _handle_scan_all_alerts(args: dict) -> dict:
    return _handle_list_alerts({})


TOOL_HANDLERS: dict[str, Any] = {
    "list_workers": _handle_list_workers,
    "find_worker_by_name": _handle_find_worker_by_name,
    "list_alerts": _handle_list_alerts,
    "get_quota_balance": _handle_get_quota_balance,
    "list_obligations": _handle_list_obligations,
    "list_contracts": _handle_list_contracts,
    "list_pending_handoffs": _handle_list_pending_handoffs,
    "simulate_mtlm_levy": _handle_simulate_mtlm_levy,
    "start_compliance_workflow": _handle_start_compliance_workflow,
    "scan_all_alerts": _handle_scan_all_alerts,
}


def _build_preview(tool_name: str, args: dict) -> str:
    if tool_name == "start_compliance_workflow":
        worker_id = args.get("worker_id", "")
        doc = db.collection("workers").document(worker_id).get()
        name = worker_id
        if doc.exists:
            name = _worker_name(doc.to_dict() or {}, worker_id)
        return f"Start compliance workflow for **{name}** ({worker_id})"
    if tool_name == "scan_all_alerts":
        return "Scan all workers for compliance alerts"
    return f"Execute {tool_name}"


# ─── Public API ───────────────────────────────────────────────────────────────

def execute_tool(tool_name: str, args: dict) -> Any:
    handler = TOOL_HANDLERS.get(tool_name)
    if not handler:
        return {"error": f"Unknown tool: {tool_name}"}
    return handler(args)


def process_message(message: str, history: list, pending_tool_result: dict | None = None) -> dict:
    """
    Main entry point. Returns { reply, tool_calls, executed_results }.

    tool_calls entries:
      { id, name, args, needs_confirmation, preview? (if pending), result? (if executed) }
    """
    contents: list[types.Content] = []
    for msg in history[-10:]:
        role = "user" if msg.get("role") == "user" else "model"
        contents.append(types.Content(role=role, parts=[types.Part(text=msg.get("content", ""))]))

    if pending_tool_result:
        tool_summary = (
            f"[Tool '{pending_tool_result.get('tool_name')}' was confirmed and executed. "
            f"Result: {json.dumps(pending_tool_result.get('result', {}), default=str)}] "
            f"Please summarize the outcome for the user."
        )
        contents.append(types.Content(role="user", parts=[types.Part(text=tool_summary)]))
    else:
        contents.append(types.Content(role="user", parts=[types.Part(text=message)]))

    cfg = types.GenerateContentConfig(
        tools=[types.Tool(function_declarations=TOOL_SCHEMAS)],
        system_instruction=SYSTEM_PROMPT,
        temperature=0.2,
    )
    response = _client.models.generate_content(model=REASONING_MODEL, contents=contents, config=cfg)

    # Collect function calls from the response
    function_calls = []
    if response.candidates:
        for part in response.candidates[0].content.parts:
            if hasattr(part, "function_call") and part.function_call:
                fc = part.function_call
                function_calls.append({"name": fc.name, "args": dict(fc.args or {})})

    if not function_calls:
        return {
            "reply": response.text or "I couldn't process that. Please try rephrasing.",
            "tool_calls": [],
            "executed_results": [],
        }

    tool_calls_out = []
    executed_results = []

    for fc in function_calls:
        name, args = fc["name"], fc["args"]
        tc_id = f"{name}_{hash(str(args)) & 0xFFFFFF:06x}"

        if name in MUTATING_TOOLS:
            tool_calls_out.append({
                "id": tc_id,
                "name": name,
                "args": args,
                "needs_confirmation": True,
                "preview": _build_preview(name, args),
            })
        else:
            result = execute_tool(name, args)
            executed_results.append({"tool": name, "result": result})
            tool_calls_out.append({
                "id": tc_id,
                "name": name,
                "args": args,
                "needs_confirmation": False,
                "result": result,
            })

    # Pending confirmation — return preview without summarising
    if any(t["needs_confirmation"] for t in tool_calls_out):
        previews = "; ".join(t["preview"] for t in tool_calls_out if t["needs_confirmation"])
        return {
            "reply": f"I can do that — please confirm: {previews}",
            "tool_calls": tool_calls_out,
            "executed_results": [],
        }

    # All read-only — ask Gemini to narrate results
    results_text = json.dumps(executed_results, indent=2, default=str)
    summary_contents = contents + [
        types.Content(role="model", parts=[types.Part(text="[called tools, got results]")]),
        types.Content(
            role="user",
            parts=[types.Part(text=f"Tool results:\n{results_text}\n\nSummarize for the user in plain English.")],
        ),
    ]
    summary = _client.models.generate_content(
        model=REASONING_MODEL,
        contents=summary_contents,
        config=types.GenerateContentConfig(temperature=0.2),
    )
    return {
        "reply": summary.text or "Done.",
        "tool_calls": tool_calls_out,
        "executed_results": executed_results,
    }
